#!/bin/bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
echo findutils

# Install wget with IRI support
brew install wget --enable-iri

# Install everything else
brew install ack
brew install ctags
brew install git
brew install imagemagick
brew install lynx
brew install macvim
brew install mongodb
brew install node
brew install phantomjs
brew install postgres --no-python
brew install redis
brew install rename
brew install the_silver_searcher
brew install tmux
brew install tree
brew install webkit2png
