# The following determines where dotfiles are installed.
dotfiles=$HOME/.dotfiles

# Source oh-my-zsh if it is installed.
if [[ -d $HOME/.oh-my-zsh ]]; then
  # Path to your oh-my-zsh configuration.
  ZSH=$HOME/.oh-my-zsh

  # Set name of the theme to load.
  ZSH_THEME="alanpeabody"

  # Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
  # Example format: plugins=(rails git textmate ruby lighthouse)
  plugins=(vi-mode ruby rbenv zsh-syntax-highlighting history-substring-search knife cap composer vagrant)

  # Source Robby's Oh-my-zsh
  source $ZSH/oh-my-zsh.sh # OMZ Robby Russell (https://github.com/robbyrussell/oh-my-zsh)
fi

# Configuration
for config_file ($dotfiles/zsh/*.zsh) source $config_file

# Put secret configuration settings in ~/.secrets
if [[ -a ~/.secrets ]] then
  source ~/.secrets
fi

if which rbenv > /dev/null; then
  eval "$(rbenv init -)";
fi